version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: .
    command: python studentManagementSystem/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/studentManagementSystem
    env_file:
      - .env.dev
    environment:
      DJANGO_SETTINGS_MODULE: studentManagementSystem.settings
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
